(defpackage :roman-numerals
  (:use :cl)
  (:export :romanize))

(in-package :roman-numerals)

(defun romanize (number)
  "Returns the Roman numeral representation for a given number."
  (let ((output '()))
    (loop while (> number 0)
          do (cond
              ((>= number 1000)
                  (setq number (- number 1000))
                  (push #\M output))
               ((>= number 900)
                  (setq number (- number 900))
                  (push #\C output)
                  (push #\M output))
              ((>= number 500)
                  (setq number (- number 500))
                  (push #\D output))
               ((>= number 400)
                  (setq number (- number 400))
                  (push #\C output)
                  (push #\D output))
              ((>= number 100)
                  (setq number (- number 100))
                  (push #\C output))
               ((>= number 90)
                  (setq number (- number 90))
                  (push #\X output)
                  (push #\C output))
              ((>= number 50)
                  (setq number (- number 50))
                  (push #\L output))
               ((>= number 40)
                  (setq number (- number 40))
                  (push #\X output)
                  (push #\L output))
              ((>= number 10)
                  (setq number (- number 10))
                  (push #\X output))
               ((>= number 9)
                  (setq number (- number 9))
                  (push #\I output)
                  (push #\X output))
               ((>= number 5)
                  (setq number (- number 5))
                  (push #\V output))
               ((>= number 4)
                  (setq number (- number 4))
                  (push #\I output)
                  (push #\V output))
              (t 
                  (setq number (- number 1))
                  (push #\I output))))
       (coerce (reverse output) 'string)))
             
    
