(defpackage :scrabble-score
  (:use :cl)
  (:export :score-word))

(in-package :scrabble-score)

(defvar *scrabble-letters* '(
                             (#\A . 1)
                             (#\E . 1)
                             (#\I . 1)
                             (#\O . 1)
                             (#\U . 1)
                             (#\L . 1)
                             (#\N . 1)
                             (#\R . 1)
                             (#\S . 1)
                             (#\T . 1)
                             (#\D . 2)
                             (#\G . 2)
                             (#\B . 3)
                             (#\C . 3)
                             (#\M . 3)
                             (#\P . 3)
                             (#\F . 4)
                             (#\H . 4)
                             (#\V . 4)
                             (#\W . 4)
                             (#\Y . 4)
                             (#\K . 5)
                             (#\J . 8)
                             (#\X . 8)
                             (#\Q . 10)
                             (#\Z . 10)
                             ))

(defun score-word (word)
  (loop for i from 0 below (length word)
        for c = (char word i)
        sum (cdr (assoc (char-upcase c) *scrabble-letters*))))
